### ISSUE TITLE
Milestone not closed

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.IntelliJ.Recipe#22]
While https://ci.appveyor.com/project/cakebuild/cake-rider/builds/37136104 was a success the CI failed to close [Milestone 0.1.0](https://github.com/cake-build/cake-rider/milestone/1)

**Comment by gep13** [comment]
Looks like those credentials are missing too ☹️

**Comment by nils-a** [comment]
Good catch. Didn't even think of the credentials. (Simply dumped the ticket here, to re-visit later)

Let's assume it's the missing credentials and close this ticket.
