### ISSUE TITLE
check whether having a no-code-csproj to generate the nupkg is better or worse than having a nuspec

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.IntelliJ.Recipe#4]
or whether it is simply "different"..

**Comment by nils-a** [comment]
@gep13 what do you think of this setup?
It enables me to use some of the features/rules we implemented in `CakeContrib.Guidelines`.

**Comment by gep13** [comment]
I am not sure if I follow the question here, sorry. Can you elaborate?

**Comment by nils-a** [comment]
this project has no `nuspec`, nut rather uses a [`csproj`](https://github.com/nils-a/Cake.IntelliJ.Recipe/blob/develop/src/Cake.IntelliJ.Recipe/Cake.IntelliJ.Recipe.csproj) with `<IncludeBuildOutput>false</IncludeBuildOutput>`.

So the empty dll that is being generated is not included in the resulting nupkg. However, everything under `content` still is packaged.

This results in the same "ouptut" as say Cake.Recipe (using a `nuspec`) but gives me the benefit of having `CakeContrib.Guidelines` to provided (at least) some guidelines (and the icon).

But it also comes with the "overhead" to maintain a `sln` and a `csproj` instead of one `nuspec`. (Which could be counter-intuitive)

**Comment by gep13** [comment]
Ah, I see what you mean now!

I think I like it! As you say, would enable things like the analyser package.

Haven't checked as only on my phone, but are you using Cake.Recipe to build the project? Does this work?

**Comment by nils-a** [comment]
I am and it sure does! 🚀

**Comment by gep13** [comment]
Sweet! 😂

**Comment by nils-a** [comment]
Seems this is fine. I'll leave it, as is.
